backend:
  name: github
  repo: anthx/anthony-carrick-blog

local_backend: true

media_folder: content/assets/images
public_folder: ../assets/images

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: created, label: Date, widget: date }
      - { name: updated, label: Modified Date, widget: date }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: false
        default: ["news"]
      - { name: title, label: Title }
      - { name: excerpt, label: Excerpt }
      - { name: body, label: Body, widget: markdown }
      - label: Featured Image
        name: featuredImage
        widget: "image"
        choose_url: true
        default: "/assets/images/Text-Blog-Featured-Image.png"
        media_library:
          config:
            multiple: true
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: excerpt, label: Excerpt }
      - { name: body, label: Body, widget: markdown }